// Code generated by protoc-gen-grpc-gateway
// source: player2.proto
// DO NOT EDIT!

/*
Package player is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package player

import (
	"encoding/json"
	"io"
	"net/http"

	"github.com/gengo/grpc-gateway/runtime"
	"github.com/gengo/grpc-gateway/utilities"
	"github.com/golang/glog"
	"github.com/golang/protobuf/proto"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
)

var _ codes.Code
var _ io.Reader
var _ = runtime.String
var _ = json.Marshal
var _ = utilities.PascalFromSnake

func request_Player_GetTime_0(ctx context.Context, client PlayerClient, req *http.Request, pathParams map[string]string) (proto.Message, error) {
	var protoReq GetTimeRequest

	return client.GetTime(ctx, &protoReq)
}

// RegisterPlayerHandlerFromEndpoint is same as RegisterPlayerHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterPlayerHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string) (err error) {
	conn, err := grpc.Dial(endpoint, grpc.WithInsecure())
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				glog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				glog.Errorf("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterPlayerHandler(ctx, mux, conn)
}

// RegisterPlayerHandler registers the http handlers for service Player to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterPlayerHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	client := NewPlayerClient(conn)

	mux.Handle("GET", pattern_Player_GetTime_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		resp, err := request_Player_GetTime_0(runtime.AnnotateContext(ctx, req), client, req, pathParams)
		if err != nil {
			runtime.HTTPError(ctx, w, err)
			return
		}

		forward_Player_GetTime_0(ctx, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_Player_GetTime_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"time"}, ""))
)

var (
	forward_Player_GetTime_0 = runtime.ForwardResponseMessage
)
